### PR TITLE
Update some bits for V2.9.1

### PR DESCRIPTION
**Pull request by ddpbsd**
~~Still undocumented:~~

~~- nodiff~~
~~- Slack notification~~

### CODE REVIEW

**Comment by nbuuck** [comment]
@ddpbsd Should an issue be opened for the two undocumented features you mentioned in this PR?

**Comment by ddpbsd** [comment]
That won't be necessary, I'm looking into them now. Thanks

**Comment by ddpbsd** [comment]
Whoops! `nodiff` already has documentation. Updating it to reflect that it was introduced in 2.9.1, not 3.0

**Comment by ddpbsd** [comment]
And it doesn't look like some of the other AR scripts are actually documented. I'll open a ticket on that.

**Pull request closed without merging**
