### PR TITLE
Site intergration and update

### PR DESCRIPTION
**Pull request by jrossi**
This is to bring all the change and make the website completely hosted on github.com this will also push the pages into github after they get built by travis ci.  This has not been setup but the docs are clear: https://github.com/Syntaf/travis-sphinx on how to make this work.  

@vichargrave Sorry I did not keep your git commits, but it was much simpler this way and cherry picking was failing all kinds of way.

### CODE REVIEW

**Comment by jrossi** [comment]
Here is what I think should happen:

- someone accept this pull request 
- this will make Travis create a gh-pages branch and push the generated html to github
- once we verify it looks right we can rename the repo to be the ossec.github.net and also can add the CNAME stuff that github recommends: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by jrossi** [comment]
Ohh and we have to disable the readthedocs hook in github.

**Comment by ddpbsd** [comment]
This is a huge change, I was hoping to be able to look it over a bit more before I accepted it. But if you'd rather we can accept it and just deal with potential fall out after.

**Comment by jrossi** [comment]
let me know and I will move forward when others have reviewed.

**Comment by ddpbsd** [comment]
Should dcid be removed from the OSSEC team since he isn't an active participant? We could add a Contributors or HIstorical members or something section and toss him and mstarks in there.

**Comment by jrossi** [comment]
I tried not to change things outside formatting and big error for the new system.  Looks like Vic dos the same. So that might make this a second pull request?

**Comment by ddpbsd** [comment]
Good idea.

**Comment by ddpbsd** [comment]
Builds for me, and looks good.

**Pull request merged**
