### PR TITLE
Make href to CSS use HTTPS

### PR DESCRIPTION
**Pull request by nbuuck**
Chrome blocks this ref due to mixed content restriction.

### CODE REVIEW

**Comment by ddpbsd** [comment]
I'll have to figure out what to do about the ablog issue before I can merge this.

**Comment by nbuuck** [comment]
The ablog issues were impacting my local build environment but don't seem - at face value - to be relevant to the travis-ci build (yet). Rather, the failure is occurring in docutils, though it's possible the root cause is still something occurring in ablog or content that depends on ablog. Regardless, I realized when I made this PR that it might not be merged until CI is working again - just wanted to get it queued. Thanks, @ddpbsd!

**Comment by nbuuck** [comment]
Added a debugging message and discovered that `make html` is choking on indexing `/blog/author/scott-r-shinn`:

```
generating indices... genindex
docname = blog/author/scott-r-shinn

Exception occurred:
  File "/usr/local/lib/python2.7/site-packages/docutils/nodes.py", line 567, in __getitem__
    return self.attributes[key]
KeyError: 'source'
```

Documents in that path are likely dynamically generated if I had to guess.

**Comment by nbuuck** [comment]
Because there's no explicit title being passed, docutils tries to get the file source path but because these aren't real files and are presumably being dynamically generated, there's no `source` key in the `self.attributes` dict.

**Pull request merged**
