### PR TITLE
Add gpg keys to the dev info

### PR DESCRIPTION
**Pull request by ddpbsd**

### CODE REVIEW

**Comment by atomicturtle** [comment]
It is awesome that you did this.

**Comment by vichargrave** [comment]
Yeah good work.  Are these built into the build packages?  If so, I think
we need to update the GPG verification steps on the Downloads page.

**Comment by atomicturtle** [comment]
Yeah, the "Atomicorp PGP key" is the public key for the RPM packages. It wouldnt hurt for all of us to sign each others keys too

**Comment by vichargrave** [comment]
Scott,

Which of these keys to you use:

   (1) DSA and ElGamal (default)
   (2) DSA (sign only)
   (4) ElGamal (sign and encrypt)

**Pull request merged**
