### PR TITLE
Fix some broken links

### PR DESCRIPTION
**Pull request by ddpbsd**
Broken links reported by rpr via email.

Unfortunately I can no longer test these changes locally, so hopefully this all works.

### CODE REVIEW

**Comment by nbuuck** [comment]
@ddpbsd Is your local build environment broken? Possibly after updating packages? I tried establishing a build environment but kept running into an issue importing make_admonition similar to this Issue: https://github.com/abakan/ablog/issues/78

**Comment by ddpbsd** [comment]
I'm having similar issues, and don't have the time to look into them at the moment. It looks like I have an old setup still around (for now, desperately needs an update), so I can use that for now.

**Comment by ddpbsd** [comment]
But it looks like something is broken with travis, so I guess I get to dig into that disaster.

**Comment by nbuuck** [comment]
I spent an hour or so trying to fix each subsequent exception being thrown during `make html`, though some of the earlier failures were similarly occurring in `conf.py`. First I patched the `import` statements in the ablog pip package, then a missing template (catalog.html) that I had to copy from ablog install directory in /usr/lib, then I ran into a wall on failures in the sphinx package related to non-existent dictionary members in `self.document.settings.env` or `self.env` as mentioned [here](https://github.com/sphinx-doc/sphinx/issues/3871). At no point did I reach the same error that is being thrown during the travisci build. It may be more productive at this point to downgrade the installed version of the different dependencies on my dev box to the minimal versions in `requirements.txt` and downgrade python to something in the same era.

**Comment by ddpbsd** [comment]
I'm guessing we'll have to turn off the blog side of things and either look for a replacement or wait for them to fix the problems.

**Pull request merged**
